package moe.leekcake.we.basekit

import org.json.JSONObject
import java.io.File
import java.io.FileWriter

class Builder(val project: Project) {
    fun build(outputDir: File) {
        outputDir.mkdirs()

        val result = JSONObject()
        result.put("warning", "It's machine generated by WE-BaseKit, Do not edit this file")
        result.put("file", "index.html")
        result.put("title", project.title)

        val general = JSONObject()
        general.put("supportsaudioprocessing", project.supportAudioProcessing)

        val properties = JSONObject()

        for((order, configure) in project.configures.withIndex()) {
            properties.put(configure.name, configure.save().put("order", order))
        }
        general.put("properties", properties)

        val localization = JSONObject()

        val langMap = HashMap<String, JSONObject>()
        for(_localization in project.localizations) {
            for(localizationData in _localization.datas) {
                if(!langMap.containsKey(localizationData.lang)) {
                    langMap[localizationData.lang] = JSONObject()
                }
                langMap[localizationData.lang]!!.put(_localization.name, localizationData.text)
            }
        }

        for(lang in langMap.keys) {
            localization.put(lang, langMap[lang])
        }

        general.put("localization", localization)

        result.put("general", general)

        result.write( FileWriter( File(outputDir, "project.json") ) ).close()
    }
}