package moe.leekcake.we.basekit

import org.json.JSONObject
import java.io.File
import java.io.FileWriter

class Builder(val project: Project) {
    fun build(outputDir: File) {
        outputDir.mkdirs()

        val result = JSONObject()
        result.put("warning", "It's machine generated by WE-BaseKit, Do not edit this file")
        result.put("file", "index.html")
        result.put("title", project.title)

        val general = JSONObject()
        general.put("supportsaudioprocessing", project.supportAudioProcessing)

        val properties = JSONObject()

        for((order, configure) in project.configures.withIndex()) {
            properties.append(configure.name, configure.save().put("order", order))
        }
        general.put("properties", properties)

        val localization = JSONObject()

        val langMap = HashMap<String, ArrayList<Localization>>()
        for(localizationData in project.localizations) {
            if(!langMap.containsKey(localizationData.lang)) {
                langMap[localizationData.lang] = ArrayList()
            }
            langMap[localizationData.lang]?.add(localizationData)
        }

        for(lang in langMap.keys) {
            val values = JSONObject()

            for(localizationData in project.localizations) {
                values.put(localizationData.name, localizationData.text)
            }

            localization.put(lang, values)
        }

        general.put("localization", localization)

        result.put("general", general)

        result.write( FileWriter( File(outputDir, "project.json") ) ).close()
    }
}